version: '3'

services:
  db:
    # image: 'postgres:latest'
    image: 'postgres:14.1'
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    env_file:
     - ./server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
      # hide these in the .env file
    # # not sure if this is working yet... wont need for production though
    volumes:
      - ./server/database:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - appnetwork
  
  server:
    # image: server
    build: ./server
    container_name: server
    volumes:
      - ./server:/server
      # - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    env_file:
     - ./server/.env
    # environment:
      # DATABASE_URL: postgres://postgres:docker@db:5432/postgres
    # also a common variable:
      # DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/postgres
    networks:
      - appnetwork
    depends_on:
      - db

  ui:
    build: ./ui
    # image: ui
    container_name: ui
    # environment:
    #   - FAST_REFRESH=false
    volumes:
      - ./ui:/src/app
    ports: 
      - '3000:3000'
    env_file:
      - ./ui/.env
    depends_on:
      - server
  
networks:
  appnetwork:
    driver: bridge